
version: '3.7'
services:
    flask:
        build: ./flask
        container_name: flask
        restart: always
        env_file:
            - ./.env.dev
        expose:
            - 8080
        links:
            - postgres:postgres
        volumes:
            - web-data:/home/ubuntu/flask
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"

    data:
        image: postgres:latest
        volumes:
        - db-data:/home/ubuntu/postgres
        command: "true"

    postgres:
        restart: always
        image: postgres:latest
        volumes:
        - db-data:/home/ubuntu/postgres
        ports:
        - "5432:5432"

    volumes:
        db-data:
        web-data: